version: "3.8"

services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.backend
    container_name: bmi-chat-backend
    restart: unless-stopped
    ports:
      - "3006:3006"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - API_WORKERS=2
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    networks:
      - bmi-chat-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:3006/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.frontend
    container_name: bmi-chat-frontend
    restart: unless-stopped
    ports:
      - "8095:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bmi-chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx Reverse Proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: bmi-chat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deployment/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - bmi-chat-network
    profiles:
      - production

volumes:
  backend_data:
  backend_logs:

networks:
  bmi-chat-network:
    driver: bridge 